# This is a basic workflow to help you get started with Actions

name: manual-image-sync
on:
  workflow_dispatch:

env:
  IMAGE_SYNCER_VERSION: v1.3.1
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

jobs:
  image-sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: install image-sync tool
      run: |
        wget https://github.com/AliyunContainerService/image-syncer/releases/download/${IMAGE_SYNCER_VERSION}/image-syncer-${IMAGE_SYNCER_VERSION}-linux-amd64.tar.gz
        tar -zxf image-syncer-${IMAGE_SYNCER_VERSION}-linux-amd64.tar.gz
        
    - name: init manual.yaml with env
      run: |
        sed -i "s#USERNAME#${DOCKERHUB_USERNAME}#g" manual.yaml
        sed -i "s#PASSWORD#${DOCKERHUB_PASSWORD}#g" manual.yaml
        
    - name: sync images
      run: |
        ./image-syncer --proc=20 --config=manual.yaml --retries=1
